-- PostgreSQL Performance Audit — SchoolWeb
-- Generated by Sira, 2026-07-02
-- Run: docker exec schoolweb-db psql -U postgres -d schoolweb -f this_file.sql

-- ═══════════════════════════════════════════
-- PROBLEM: posts frequently filtered by category + is_published + date
-- Current: sequential scan on 62+ rows (will grow)
-- Fix: composite index for the most common query pattern
-- ═══════════════════════════════════════════
CREATE INDEX IF NOT EXISTS posts_category_published_date_idx
  ON posts (category, is_published, published_at DESC);

-- ═══════════════════════════════════════════
-- PROBLEM: achievements filtered by category + level + is_featured
-- Current: sequential scan
-- ═══════════════════════════════════════════
CREATE INDEX IF NOT EXISTS achievements_featured_idx
  ON achievements (is_featured, is_published, date DESC)
  WHERE is_featured = true AND is_published = true;

-- ═══════════════════════════════════════════
-- PROBLEM: facilities filtered by category
-- ═══════════════════════════════════════════
CREATE INDEX IF NOT EXISTS facilities_category_idx
  ON facilities (category, is_published);

-- ═══════════════════════════════════════════
-- PROBLEM: staff ordered by sort_order + filtered by is_active
-- ═══════════════════════════════════════════
CREATE INDEX IF NOT EXISTS staff_active_sort_idx
  ON staff (is_active, sort_order)
  WHERE is_active = true;

-- ═══════════════════════════════════════════
-- PROBLEM: sessions lookup by token (already has index, but verify)
-- ═══════════════════════════════════════════
-- Already exists: sessions_token_unique on (token)

-- Verify after running:
-- SELECT * FROM pg_stat_user_tables WHERE seq_scan > 0 ORDER BY seq_scan DESC;
